* lem

=lem= is an Emacs client library for Lemmy, the federated link-aggregator. For information about Lemmy, see [[http://joinlemmy.org][joinlemmy.org]].

All functions make requests and return JSON data pased into Elisp.

The idea is that it's then possible to write different frontends so users can read lemmy posts in whatever forms they like. Possibilities are notmuch, gnus, md4rd, elfeed, or a standalone rendering option more like mastodon.el.

Currently, most of the basic endpoints are implemented, but not all parameters for each endpoint. 

* Logging in

See =lem-login= and =lem-login-set-token=. Lemmy seems to just require an =auth= parameter with a token you receive as a response to logging in. Currently this token is saved to the persistent variable =lem-auth-token=, which is probably not smart, but it's easy.

* dependency

=lem= depends on [[https://codeberg.org/martianh/fedi.el][fedi.el]], a library to make writing a library of API requests easier.

* TODOS (UI layer)

- [X] view instance
- [X] list communities
- [X] view community
- [X] view post and comments
- [X] adjust listing type and sort for views
- [X] buffer macro
- [X] simple reply
- [X] subscribe to community
- [ ] buffer naming/separation
- [ ] pagination
- [ ] complete implementing of limit
- [ ] rich text rendering of content and bylines
- [ ] tabstop logic (from mastodon.el)
- [ ] timestamp logic (from mastodon.el)
- [ ] rich compose interface (from mastodon.el)
- [ ] working full comment threads
- [ ] search
